# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen+github@gmail.com
author_name: Konrad Jelen
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterlab_share_files_extension
project_short_description: A JupyterLab extension.
python_name: jupyterlab_share_files_extension
repository: ''
test: true

